# Generated by Django 5.1.3 on 2024-11-25 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_buyer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
